name: Lint and Test on Push

on: [push]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Sets up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      # Install dependencies
      - name: Install dependencies
        run: yarn

      # Upload node_modules folder for the lint job
      - name: Upload build folder
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules/

  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v2

      # Download the node_modules folder
      - name: Download node_modules folder
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules/

      # Sets up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      # Lint the code
      - name: Lint project code
        run: yarn lint
