name: Build and Deploy Website

on:
  push:
    branches: [ develop, feature/github_actions ]
  pull_request:
    branches: [ develop, feature/github_actions ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Sets up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      # Build the project
      - name: Build project
        run: |
          yarn
          yarn build

      # Upload build folder for the deploy job
      - name: Upload build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy:
    name: Deploy Project
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Download the build folder
      - name: Download build folder
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      # Deploy to gh pages website (development)
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.ref == 'refs/heads/develop'
        with:
          repository-name: AmazonPriime/amazonpriime.github.io
          branch: main
          folder: build
          target-folder: indproj-dev
          clean: true
          token: ${{ secrets.PAT }}

      # Deploy to gh pages website (production)
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.ref == 'refs/heads/main'
        with:
          repository-name: AmazonPriime/amazonpriime.github.io
          branch: main
          folder: build
          target-folder: indproj
          clean: true
          token: ${{ secrets.PAT }}
