name: Test, Build and Deploy Dev Website

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Uses yarn caching
      - uses: c-hive/gha-yarn-cache@v2

      # Lint the code
      - name: Lint project code
        run: |
          yarn
          yarn lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Uses yarn caching
      - uses: c-hive/gha-yarn-cache@v2

      # Run the tests
      - name: Run tests for project
        run: |
          yarn
          echo 'Now running tests...'

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - uses: actions/checkout@v2

      # Uses yarn caching
      - uses: c-hive/gha-yarn-cache@v2

      # Build the project
      - name: Build project
        run: |
          yarn
          yarn build

      # Upload build folder for the deploy job
      - name: Upload build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      # Download the build folder
      - name: Download build folder
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      # Deploy to github pages website
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          repository-name: AmazonPriime/amazonpriime.github.io
          branch: main
          folder: build
          target-folder: indproj-dev
          clean: true
          token: ${{ secrets.PAT }}
